DROP TABLE IF EXISTS Arvosteluasiasana CASCADE;
DROP TABLE IF EXISTS Asiasana CASCADE;
DROP TABLE IF EXISTS Arvio CASCADE;
DROP TABLE IF EXISTS Arvostelu CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
